### ISSUE TITLE
Add button "connect to metamask"

### ISSUE THREAD

**Issue by 5chdn** [goerli/GoethBridgeUI#7]
It's very intrusive to have metamask popping up without user interaction. 

Ideal workflow:

1. Tell user what a bridge faucet is
2. Tell user to set metamask to 1 testnet of {Ropsten, Rinkeby, Kovan}
3. Tell user to click the "connect to metamask" button

Would also potentially address #1

**Comment by chrisfenos** [comment]
I have closed this issue, with respect to the #1 issue I am still working on this bug -> https://github.com/MetaMask/metamask-extension/issues/4434 @5chdn
